name: FirstWorkFlow

on:
  push:
    branches: 
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Hello world bro to our first github action workflow!"

      - name : checkout repositry 
        uses: action/checkout@4.2.2
      - name: list repos
        run: ls -la
        
      
