on:
  push:
      branches:
        - main
        - "release/**"
      paths:
        - "src/**"
  pull_request:
    branches: 
      - main
      - "release/**"  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Make test script executable
        run: chmod +x test_etl.sh

      - name: Run the test script
        run: ./src/test_etl.sh
